# Generated by Django 3.2.18 on 2023-03-13 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timer',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
